### ISSUE TITLE
Show STEP file 3D content

### ISSUE THREAD

**Issue by jpopeneng** [RHEAGROUP/DEHP-STEPAP242#18]
In the PM2 meeting it was suggested a way to display the content of a STEP file, generally the intention is to visualize the complexity of the model stored in the Hub.

Probably the most customizable way to do it is by adding a "STEP Viewer" path in the _User Preferences_ of the application. If could be that default application in the system is not correct for all cases (for example simple viewer vs complex CAD systems).

**Comment by ifonsoe** [comment]
Added to the user setting dialog. The user now has the possibility either to use the system defined application or to select another application to "open" the step files.
