### ISSUE TITLE
DST-CAD-SR-0040: show HLR differences between STEP-AP242 files

### ISSUE THREAD

**Issue by jpopeneng** [RHEAGROUP/DEHP-STEPAP242#4]
The STEP 3D CAD DST adapter shall provide the analysis of differences between STEP 3D CAD files (the one provided by the user and the other stored in the data hub) only for the entities mapped in the High Level Representation.

**Comment by ifonsoe** [comment]
Fixed in d6c22d0806f80cce3875d722dbad3c6dd4b959a9
